module.exports = {
  collectCoverageFrom: [
    'App.tsx',
    'src/**/*.ts',
    'src/**/*.tsx',
    '!src/**/index.ts',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: ['text', 'lcov', 'html'],
  moduleNameMapper: {
    '^@components$': '<rootDir>/src/components',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@designsystem$': '<rootDir>/src/design',
    '^@designsystem/(.*)$': '<rootDir>/src/design/$1',
    '^@designsytem$': '<rootDir>/src/design',
    '^@designsytem/(.*)$': '<rootDir>/src/design/$1',
    '^@theme$': '<rootDir>/src/design',
    '^@theme/(.*)$': '<rootDir>/src/design/$1',
    '^@domain$': '<rootDir>/src/domain',
    '^@domain/(.*)$': '<rootDir>/src/domain/$1',
    '^@features/(.*)$': '<rootDir>/src/features/$1',
    '^@lib$': '<rootDir>/src/lib',
    '^@lib/(.*)$': '<rootDir>/src/lib/$1',
    '^@navigation$': '<rootDir>/src/navigation',
    '^@navigation/(.*)$': '<rootDir>/src/navigation/$1',
    '^@screens$': '<rootDir>/src/screens',
    '^@screens/(.*)$': '<rootDir>/src/screens/$1',
  },
  preset: 'react-native',
};
